### ISSUE TITLE
Resolver bug? “Cannot define graphql type for function”

### ISSUE THREAD

**Issue by heymartinadams** [8base/issues#43]
**Describe the bug**
Upon `8base deploy` I get the following error message:
```
error: Cannot define graphql type for function "createMessage" 
```

**To Reproduce**
### package.json
```json
{
  "dependencies": {
    "graphql-tag": "^2.10.1"
  },
  "devDependencies": {
    "graphql": "^14.4.2",
    "nodemon": "^1.19.1"
  }
}

```
### 8base.yml
```yml
functions:
  createMessage:
    handler:
      code: src/mutations/createMessage/resolver.js
    type: resolver
    schema: src/mutations/createMessage/schema.graphql
```
### src/mutations/createMessage/schema.graphql
```graphql
extend type Mutation {
  hello(name: String): HelloResult
}

type HelloResult {
  result: String!
}
```
### src/mutations/createMessage/resolver.js
```js
module.exports = event => {
  const name = event.data.name
  return {
    data: {
      result: `Hello ${name}!`
    }
  }
}
```

**Expected behavior**
Expected it to work? 😁 

**Desktop (please complete the following information):**
macOS

**Comment by eugeneantonevich** [comment]
It's expected behavior. You should define the name of custom resolver in graphql file the same as name of resolver's name in 8base.yml. For example, if you define 8base.yml like
```
functions:
  createMessage:  <-- resolver name
    handler:
      code: src/mutations/createMessage/resolver.js
    type: resolver
    schema: src/mutations/createMessage/schema.graphql
```
the schema.graphql should look like 

```
extend type Mutation {
  createMessage(name: String): HelloResult
}
type HelloResult {
  result: String!
}
```
